export const ROUTES = {
  HOME: '/',
  C: '/c',
  RESET: '/reset',
  ACCOUNT: '',
  ADDRESSES: '/addresses',
  SHOP: '',
  DASHBOARD: '/dashboard',
  SEARCH: '/search',
  CART: '/cart',
  PRODUCTS: '/products',
  SALES: '/sales',
  ORDERS: '/orders',
  CHECKOUT: '/checkout',
  SUCCESS: '/success',
  NEW: '/new',
} as const;
