export const ICON_NAME_BY_ALIAS = {
  ai: 'tabler:ai',
  search: 'i-uil:search',
  searchSolid: 'i-heroicons-magnifying-glass-20-solid',
  user: 'majesticons:user-line',
  cart: 'i-uil:cart',
  bell: 'akar-icons:bell',
  settings: 'i-heroicons-cog-8-tooth',
  orders: 'lets-icons:order',
  account: 'majesticons:user-line',
  archive: 'i-heroicons-archive-box-20-solid',
  marketplace: 'solar:shop-bold-duotone',
  logout: 'i-heroicons-arrow-left-start-on-rectangle',
  star: 'solar:star-bold',
  manageShop: 'solar:shop-linear',
  warning: 'ph:warning-duotone',
  plus: 'i-heroicons-plus',
  plusCircle: 'lucide:circle-plus',
  xCircle: 'lucide:circle-x',
  x: 'i-lucide-x',
  xMark: 'i-heroicons-x-mark',
  xMarkSolid: 'i-heroicons-x-mark-20-solid',
  minus: 'i-heroicons-minus',
  edit: 'lucide:edit',
  trash: 'i-heroicons-trash',
  close: 'i-material-symbols:cancel-rounded',
  check: 'i-material-symbols:check-circle-rounded',
  calendar: 'i-material-symbols:calendar-month-rounded',
  calendarDaysSolid: 'i-heroicons-calendar-days-20-solid',
  location: 'i-material-symbols:location-on-outline',
  arrowUp: 'lucide:arrow-up',
  arrowDown: 'lucide:arrow-down',
  arrowRight: 'lucide:arrow-right',
  arrowLeft: 'lucide:arrow-left',
  arrowForward: 'tabler:arrow-forward',
  chevronLeft: 'lucide:chevron-left',
  chevronRight: 'lucide:chevron-right',
  chevronLeftSolid: 'i-heroicons-chevron-left-20-solid',
  chevronRightSolid: 'i-heroicons-chevron-right-20-solid',
  chevronUp: 'i-heroicons-chevron-up-20-solid',
  chevronDown: 'i-heroicons-chevron-down-20-solid',
  language: 'i-heroicons-language',
  shop: 'mynaui:store',
  ticket: 'i-heroicons-ticket',
  camera: 'material-symbols:android-camera',
  message: 'tabler:message',
  shipping: 'lucide:plane',
  product: 'tabler:cube',
  dashboard: 'streamline-flex:dashboard-3',
  revenue: 'i-heroicons-banknotes-20-solid',
  averageOrder: 'i-heroicons-chart-bar-20-solid',
  marketing: 'nimbus:marketing',
  refund: 'lets-icons:refund-forward',
  expired: 'i-heroicons-clock-20-solid',
  delivered: 'hugeicons:package-delivered',
  transit: 'lucide:map',
  payment: 'fluent:payment-28-regular',
  orderCreated: 'i-heroicons-document-plus-20-solid',
  moreHorizontal: 'i-heroicons-ellipsis-horizontal-20-solid',
  clipboardDocumentList: 'i-heroicons-clipboard-document-list',
  uploadCloud: 'lucide:cloud-upload',
  ratingVeryBad: 'lucide:frown',
  ratingBad: 'lucide:annoyed',
  ratingNeutral: 'lucide:meh',
  ratingGood: 'lucide:smile',
  ratingExcellent: 'lucide:laugh',
  import: 'iconoir:import',
  export: 'ph:export',
  downloadTray: 'i-heroicons-arrow-down-tray',
} as const

export type AppIconAlias = keyof typeof ICON_NAME_BY_ALIAS

export const APP_ICON_COLLECTIONS = [
  'akar-icons',
  'fluent',
  'heroicons',
  'hugeicons',
  'iconoir',
  'lets-icons',
  'lucide',
  'majesticons',
  'material-symbols',
  'mynaui',
  'nimbus',
  'ph',
  'solar',
  'streamline-flex',
  'tabler',
  'uil',
] as const

export const APP_ICON_CLIENT_BUNDLE_ICONS = [
  'tabler:ai',
  'uil:search',
  'majesticons:user-line',
  'uil:cart',
  'akar-icons:bell',
  'heroicons:cog-8-tooth',
  'lets-icons:order',
  'heroicons:archive-box-20-solid',
  'solar:shop-bold-duotone',
  'heroicons:arrow-left-start-on-rectangle',
  'solar:star-bold',
  'solar:shop-linear',
  'ph:warning-duotone',
  'heroicons:plus',
  'lucide:circle-plus',
  'lucide:circle-x',
  'heroicons:minus',
  'lucide:edit',
  'heroicons:trash',
  'material-symbols:cancel-rounded',
  'material-symbols:check-circle-rounded',
  'material-symbols:calendar-month-rounded',
  'material-symbols:location-on-outline',
  'lucide:arrow-up',
  'lucide:arrow-down',
  'lucide:arrow-right',
  'lucide:arrow-left',
  'tabler:arrow-forward',
  'lucide:chevron-left',
  'lucide:chevron-right',
  'lucide:chevrons-left',
  'lucide:chevrons-right',
  'heroicons:chevron-up-20-solid',
  'heroicons:chevron-down-20-solid',
  'heroicons:language',
  'mynaui:store',
  'heroicons:ticket',
  'material-symbols:android-camera',
  'tabler:message',
  'lucide:plane',
  'tabler:cube',
  'streamline-flex:dashboard-3',
  'heroicons:banknotes-20-solid',
  'heroicons:chart-bar-20-solid',
  'nimbus:marketing',
  'lets-icons:refund-forward',
  'heroicons:clock-20-solid',
  'hugeicons:package-delivered',
  'lucide:map',
  'fluent:payment-28-regular',
  'heroicons:document-plus-20-solid',
  'heroicons:ellipsis-horizontal-20-solid',
  'lucide:cloud-upload',
  'lucide:frown',
  'lucide:annoyed',
  'lucide:meh',
  'lucide:smile',
  'lucide:laugh',
  'iconoir:import',
  'ph:export',
] as const

export const APPROVED_ICON_PREFIXES = [
  'i-heroicons-',
  'i-material-symbols:',
  'material-symbols:',
  'solar:',
  'i-solar:',
  'uil:',
  'i-uil:',
  'ph:',
  'majesticons:',
  'lucide:',
  'i-simple-icons:',
  'i-logos-',
] as const

export function resolveAppIconName(name?: AppIconAlias | string | null): string | undefined {
  if (!name) {
    return undefined
  }

  return ICON_NAME_BY_ALIAS[name as AppIconAlias] ?? name
}

export function resolveAppIconCssClass(name?: AppIconAlias | string | null): string | undefined {
  const resolvedName = resolveAppIconName(name)

  if (!resolvedName) {
    return undefined
  }

  if (resolvedName.startsWith('i-')) {
    return resolvedName
  }

  return `i-${resolvedName}`
}
