export enum ROUTES {
  HOME = '/',
  C = '/c',
  RESET = '/reset',
  ACCOUNT = '/account',
  ADDRESSES = '/addresses',
  SHOP = '/shop',
  DASHBOARD = '/dashboard',
  SEARCH = '/search',
  CART = '/cart',
  PRODUCTS = '/products',
  PROMO_CODES = '/promo-codes',
  SALES = '/sales',
  ORDERS = '/orders',
  CHECKOUT = '/checkout',
  SUCCESS = '/success',
  NEW = '/new',
}
